/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-06-09 16:41:44 UTC)
 * on 2014-06-27 at 07:38:28 UTC 
 * Modify at your own risk.
 */

package com.work.petcharity.kalbiyaendpoint;

/**
 * Service definition for Kalbiyaendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link KalbiyaendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Kalbiyaendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the kalbiyaendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://ardent-rarity-610.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "kalbiyaendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Kalbiyaendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Kalbiyaendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getKalbiya".
   *
   * This request holds the parameters needed by the the kalbiyaendpoint server.  After setting any
   * optional parameters, call the {@link GetKalbiya#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetKalbiya getKalbiya(java.lang.Long id) throws java.io.IOException {
    GetKalbiya result = new GetKalbiya(id);
    initialize(result);
    return result;
  }

  public class GetKalbiya extends KalbiyaendpointRequest<com.work.petcharity.kalbiyaendpoint.model.Kalbiya> {

    private static final String REST_PATH = "kalbiya/{id}";

    /**
     * Create a request for the method "getKalbiya".
     *
     * This request holds the parameters needed by the the kalbiyaendpoint server.  After setting any
     * optional parameters, call the {@link GetKalbiya#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetKalbiya#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetKalbiya(java.lang.Long id) {
      super(Kalbiyaendpoint.this, "GET", REST_PATH, null, com.work.petcharity.kalbiyaendpoint.model.Kalbiya.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetKalbiya setAlt(java.lang.String alt) {
      return (GetKalbiya) super.setAlt(alt);
    }

    @Override
    public GetKalbiya setFields(java.lang.String fields) {
      return (GetKalbiya) super.setFields(fields);
    }

    @Override
    public GetKalbiya setKey(java.lang.String key) {
      return (GetKalbiya) super.setKey(key);
    }

    @Override
    public GetKalbiya setOauthToken(java.lang.String oauthToken) {
      return (GetKalbiya) super.setOauthToken(oauthToken);
    }

    @Override
    public GetKalbiya setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetKalbiya) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetKalbiya setQuotaUser(java.lang.String quotaUser) {
      return (GetKalbiya) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetKalbiya setUserIp(java.lang.String userIp) {
      return (GetKalbiya) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetKalbiya setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetKalbiya set(String parameterName, Object value) {
      return (GetKalbiya) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertKalbiya".
   *
   * This request holds the parameters needed by the the kalbiyaendpoint server.  After setting any
   * optional parameters, call the {@link InsertKalbiya#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.work.petcharity.kalbiyaendpoint.model.Kalbiya}
   * @return the request
   */
  public InsertKalbiya insertKalbiya(com.work.petcharity.kalbiyaendpoint.model.Kalbiya content) throws java.io.IOException {
    InsertKalbiya result = new InsertKalbiya(content);
    initialize(result);
    return result;
  }

  public class InsertKalbiya extends KalbiyaendpointRequest<com.work.petcharity.kalbiyaendpoint.model.Kalbiya> {

    private static final String REST_PATH = "kalbiya";

    /**
     * Create a request for the method "insertKalbiya".
     *
     * This request holds the parameters needed by the the kalbiyaendpoint server.  After setting any
     * optional parameters, call the {@link InsertKalbiya#execute()} method to invoke the remote
     * operation. <p> {@link InsertKalbiya#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.work.petcharity.kalbiyaendpoint.model.Kalbiya}
     * @since 1.13
     */
    protected InsertKalbiya(com.work.petcharity.kalbiyaendpoint.model.Kalbiya content) {
      super(Kalbiyaendpoint.this, "POST", REST_PATH, content, com.work.petcharity.kalbiyaendpoint.model.Kalbiya.class);
    }

    @Override
    public InsertKalbiya setAlt(java.lang.String alt) {
      return (InsertKalbiya) super.setAlt(alt);
    }

    @Override
    public InsertKalbiya setFields(java.lang.String fields) {
      return (InsertKalbiya) super.setFields(fields);
    }

    @Override
    public InsertKalbiya setKey(java.lang.String key) {
      return (InsertKalbiya) super.setKey(key);
    }

    @Override
    public InsertKalbiya setOauthToken(java.lang.String oauthToken) {
      return (InsertKalbiya) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertKalbiya setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertKalbiya) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertKalbiya setQuotaUser(java.lang.String quotaUser) {
      return (InsertKalbiya) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertKalbiya setUserIp(java.lang.String userIp) {
      return (InsertKalbiya) super.setUserIp(userIp);
    }

    @Override
    public InsertKalbiya set(String parameterName, Object value) {
      return (InsertKalbiya) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listKalbiya".
   *
   * This request holds the parameters needed by the the kalbiyaendpoint server.  After setting any
   * optional parameters, call the {@link ListKalbiya#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListKalbiya listKalbiya() throws java.io.IOException {
    ListKalbiya result = new ListKalbiya();
    initialize(result);
    return result;
  }

  public class ListKalbiya extends KalbiyaendpointRequest<com.work.petcharity.kalbiyaendpoint.model.CollectionResponseKalbiya> {

    private static final String REST_PATH = "kalbiya";

    /**
     * Create a request for the method "listKalbiya".
     *
     * This request holds the parameters needed by the the kalbiyaendpoint server.  After setting any
     * optional parameters, call the {@link ListKalbiya#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListKalbiya#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListKalbiya() {
      super(Kalbiyaendpoint.this, "GET", REST_PATH, null, com.work.petcharity.kalbiyaendpoint.model.CollectionResponseKalbiya.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListKalbiya setAlt(java.lang.String alt) {
      return (ListKalbiya) super.setAlt(alt);
    }

    @Override
    public ListKalbiya setFields(java.lang.String fields) {
      return (ListKalbiya) super.setFields(fields);
    }

    @Override
    public ListKalbiya setKey(java.lang.String key) {
      return (ListKalbiya) super.setKey(key);
    }

    @Override
    public ListKalbiya setOauthToken(java.lang.String oauthToken) {
      return (ListKalbiya) super.setOauthToken(oauthToken);
    }

    @Override
    public ListKalbiya setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListKalbiya) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListKalbiya setQuotaUser(java.lang.String quotaUser) {
      return (ListKalbiya) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListKalbiya setUserIp(java.lang.String userIp) {
      return (ListKalbiya) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListKalbiya setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListKalbiya setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListKalbiya set(String parameterName, Object value) {
      return (ListKalbiya) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeKalbiya".
   *
   * This request holds the parameters needed by the the kalbiyaendpoint server.  After setting any
   * optional parameters, call the {@link RemoveKalbiya#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveKalbiya removeKalbiya(java.lang.Long id) throws java.io.IOException {
    RemoveKalbiya result = new RemoveKalbiya(id);
    initialize(result);
    return result;
  }

  public class RemoveKalbiya extends KalbiyaendpointRequest<Void> {

    private static final String REST_PATH = "kalbiya/{id}";

    /**
     * Create a request for the method "removeKalbiya".
     *
     * This request holds the parameters needed by the the kalbiyaendpoint server.  After setting any
     * optional parameters, call the {@link RemoveKalbiya#execute()} method to invoke the remote
     * operation. <p> {@link RemoveKalbiya#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveKalbiya(java.lang.Long id) {
      super(Kalbiyaendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveKalbiya setAlt(java.lang.String alt) {
      return (RemoveKalbiya) super.setAlt(alt);
    }

    @Override
    public RemoveKalbiya setFields(java.lang.String fields) {
      return (RemoveKalbiya) super.setFields(fields);
    }

    @Override
    public RemoveKalbiya setKey(java.lang.String key) {
      return (RemoveKalbiya) super.setKey(key);
    }

    @Override
    public RemoveKalbiya setOauthToken(java.lang.String oauthToken) {
      return (RemoveKalbiya) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveKalbiya setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveKalbiya) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveKalbiya setQuotaUser(java.lang.String quotaUser) {
      return (RemoveKalbiya) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveKalbiya setUserIp(java.lang.String userIp) {
      return (RemoveKalbiya) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveKalbiya setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveKalbiya set(String parameterName, Object value) {
      return (RemoveKalbiya) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateKalbiya".
   *
   * This request holds the parameters needed by the the kalbiyaendpoint server.  After setting any
   * optional parameters, call the {@link UpdateKalbiya#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.work.petcharity.kalbiyaendpoint.model.Kalbiya}
   * @return the request
   */
  public UpdateKalbiya updateKalbiya(com.work.petcharity.kalbiyaendpoint.model.Kalbiya content) throws java.io.IOException {
    UpdateKalbiya result = new UpdateKalbiya(content);
    initialize(result);
    return result;
  }

  public class UpdateKalbiya extends KalbiyaendpointRequest<com.work.petcharity.kalbiyaendpoint.model.Kalbiya> {

    private static final String REST_PATH = "kalbiya";

    /**
     * Create a request for the method "updateKalbiya".
     *
     * This request holds the parameters needed by the the kalbiyaendpoint server.  After setting any
     * optional parameters, call the {@link UpdateKalbiya#execute()} method to invoke the remote
     * operation. <p> {@link UpdateKalbiya#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.work.petcharity.kalbiyaendpoint.model.Kalbiya}
     * @since 1.13
     */
    protected UpdateKalbiya(com.work.petcharity.kalbiyaendpoint.model.Kalbiya content) {
      super(Kalbiyaendpoint.this, "PUT", REST_PATH, content, com.work.petcharity.kalbiyaendpoint.model.Kalbiya.class);
    }

    @Override
    public UpdateKalbiya setAlt(java.lang.String alt) {
      return (UpdateKalbiya) super.setAlt(alt);
    }

    @Override
    public UpdateKalbiya setFields(java.lang.String fields) {
      return (UpdateKalbiya) super.setFields(fields);
    }

    @Override
    public UpdateKalbiya setKey(java.lang.String key) {
      return (UpdateKalbiya) super.setKey(key);
    }

    @Override
    public UpdateKalbiya setOauthToken(java.lang.String oauthToken) {
      return (UpdateKalbiya) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateKalbiya setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateKalbiya) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateKalbiya setQuotaUser(java.lang.String quotaUser) {
      return (UpdateKalbiya) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateKalbiya setUserIp(java.lang.String userIp) {
      return (UpdateKalbiya) super.setUserIp(userIp);
    }

    @Override
    public UpdateKalbiya set(String parameterName, Object value) {
      return (UpdateKalbiya) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Kalbiyaendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Kalbiyaendpoint}. */
    @Override
    public Kalbiyaendpoint build() {
      return new Kalbiyaendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link KalbiyaendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setKalbiyaendpointRequestInitializer(
        KalbiyaendpointRequestInitializer kalbiyaendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(kalbiyaendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
