/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-06-30 15:48:57 UTC)
 * on 2014-07-12 at 07:43:37 UTC 
 * Modify at your own risk.
 */

package com.work.petcharity.paymentsendpoint;

/**
 * Service definition for Paymentsendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link PaymentsendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Paymentsendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the paymentsendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://petcharity-admin-app-32.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "paymentsendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Paymentsendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Paymentsendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getPayments".
   *
   * This request holds the parameters needed by the the paymentsendpoint server.  After setting any
   * optional parameters, call the {@link GetPayments#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetPayments getPayments(java.lang.Long id) throws java.io.IOException {
    GetPayments result = new GetPayments(id);
    initialize(result);
    return result;
  }

  public class GetPayments extends PaymentsendpointRequest<com.work.petcharity.paymentsendpoint.model.Payments> {

    private static final String REST_PATH = "payments/{id}";

    /**
     * Create a request for the method "getPayments".
     *
     * This request holds the parameters needed by the the paymentsendpoint server.  After setting any
     * optional parameters, call the {@link GetPayments#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetPayments#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetPayments(java.lang.Long id) {
      super(Paymentsendpoint.this, "GET", REST_PATH, null, com.work.petcharity.paymentsendpoint.model.Payments.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPayments setAlt(java.lang.String alt) {
      return (GetPayments) super.setAlt(alt);
    }

    @Override
    public GetPayments setFields(java.lang.String fields) {
      return (GetPayments) super.setFields(fields);
    }

    @Override
    public GetPayments setKey(java.lang.String key) {
      return (GetPayments) super.setKey(key);
    }

    @Override
    public GetPayments setOauthToken(java.lang.String oauthToken) {
      return (GetPayments) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPayments setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPayments) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPayments setQuotaUser(java.lang.String quotaUser) {
      return (GetPayments) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPayments setUserIp(java.lang.String userIp) {
      return (GetPayments) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetPayments setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetPayments set(String parameterName, Object value) {
      return (GetPayments) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertPayments".
   *
   * This request holds the parameters needed by the the paymentsendpoint server.  After setting any
   * optional parameters, call the {@link InsertPayments#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.work.petcharity.paymentsendpoint.model.Payments}
   * @return the request
   */
  public InsertPayments insertPayments(com.work.petcharity.paymentsendpoint.model.Payments content) throws java.io.IOException {
    InsertPayments result = new InsertPayments(content);
    initialize(result);
    return result;
  }

  public class InsertPayments extends PaymentsendpointRequest<com.work.petcharity.paymentsendpoint.model.Payments> {

    private static final String REST_PATH = "payments";

    /**
     * Create a request for the method "insertPayments".
     *
     * This request holds the parameters needed by the the paymentsendpoint server.  After setting any
     * optional parameters, call the {@link InsertPayments#execute()} method to invoke the remote
     * operation. <p> {@link InsertPayments#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.work.petcharity.paymentsendpoint.model.Payments}
     * @since 1.13
     */
    protected InsertPayments(com.work.petcharity.paymentsendpoint.model.Payments content) {
      super(Paymentsendpoint.this, "POST", REST_PATH, content, com.work.petcharity.paymentsendpoint.model.Payments.class);
    }

    @Override
    public InsertPayments setAlt(java.lang.String alt) {
      return (InsertPayments) super.setAlt(alt);
    }

    @Override
    public InsertPayments setFields(java.lang.String fields) {
      return (InsertPayments) super.setFields(fields);
    }

    @Override
    public InsertPayments setKey(java.lang.String key) {
      return (InsertPayments) super.setKey(key);
    }

    @Override
    public InsertPayments setOauthToken(java.lang.String oauthToken) {
      return (InsertPayments) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertPayments setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertPayments) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertPayments setQuotaUser(java.lang.String quotaUser) {
      return (InsertPayments) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertPayments setUserIp(java.lang.String userIp) {
      return (InsertPayments) super.setUserIp(userIp);
    }

    @Override
    public InsertPayments set(String parameterName, Object value) {
      return (InsertPayments) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listPayments".
   *
   * This request holds the parameters needed by the the paymentsendpoint server.  After setting any
   * optional parameters, call the {@link ListPayments#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListPayments listPayments() throws java.io.IOException {
    ListPayments result = new ListPayments();
    initialize(result);
    return result;
  }

  public class ListPayments extends PaymentsendpointRequest<com.work.petcharity.paymentsendpoint.model.CollectionResponsePayments> {

    private static final String REST_PATH = "payments";

    /**
     * Create a request for the method "listPayments".
     *
     * This request holds the parameters needed by the the paymentsendpoint server.  After setting any
     * optional parameters, call the {@link ListPayments#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListPayments#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListPayments() {
      super(Paymentsendpoint.this, "GET", REST_PATH, null, com.work.petcharity.paymentsendpoint.model.CollectionResponsePayments.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListPayments setAlt(java.lang.String alt) {
      return (ListPayments) super.setAlt(alt);
    }

    @Override
    public ListPayments setFields(java.lang.String fields) {
      return (ListPayments) super.setFields(fields);
    }

    @Override
    public ListPayments setKey(java.lang.String key) {
      return (ListPayments) super.setKey(key);
    }

    @Override
    public ListPayments setOauthToken(java.lang.String oauthToken) {
      return (ListPayments) super.setOauthToken(oauthToken);
    }

    @Override
    public ListPayments setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListPayments) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListPayments setQuotaUser(java.lang.String quotaUser) {
      return (ListPayments) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListPayments setUserIp(java.lang.String userIp) {
      return (ListPayments) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListPayments setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListPayments setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListPayments set(String parameterName, Object value) {
      return (ListPayments) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removePayments".
   *
   * This request holds the parameters needed by the the paymentsendpoint server.  After setting any
   * optional parameters, call the {@link RemovePayments#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemovePayments removePayments(java.lang.Long id) throws java.io.IOException {
    RemovePayments result = new RemovePayments(id);
    initialize(result);
    return result;
  }

  public class RemovePayments extends PaymentsendpointRequest<Void> {

    private static final String REST_PATH = "payments/{id}";

    /**
     * Create a request for the method "removePayments".
     *
     * This request holds the parameters needed by the the paymentsendpoint server.  After setting any
     * optional parameters, call the {@link RemovePayments#execute()} method to invoke the remote
     * operation. <p> {@link RemovePayments#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemovePayments(java.lang.Long id) {
      super(Paymentsendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemovePayments setAlt(java.lang.String alt) {
      return (RemovePayments) super.setAlt(alt);
    }

    @Override
    public RemovePayments setFields(java.lang.String fields) {
      return (RemovePayments) super.setFields(fields);
    }

    @Override
    public RemovePayments setKey(java.lang.String key) {
      return (RemovePayments) super.setKey(key);
    }

    @Override
    public RemovePayments setOauthToken(java.lang.String oauthToken) {
      return (RemovePayments) super.setOauthToken(oauthToken);
    }

    @Override
    public RemovePayments setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemovePayments) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemovePayments setQuotaUser(java.lang.String quotaUser) {
      return (RemovePayments) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemovePayments setUserIp(java.lang.String userIp) {
      return (RemovePayments) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemovePayments setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemovePayments set(String parameterName, Object value) {
      return (RemovePayments) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updatePayments".
   *
   * This request holds the parameters needed by the the paymentsendpoint server.  After setting any
   * optional parameters, call the {@link UpdatePayments#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.work.petcharity.paymentsendpoint.model.Payments}
   * @return the request
   */
  public UpdatePayments updatePayments(com.work.petcharity.paymentsendpoint.model.Payments content) throws java.io.IOException {
    UpdatePayments result = new UpdatePayments(content);
    initialize(result);
    return result;
  }

  public class UpdatePayments extends PaymentsendpointRequest<com.work.petcharity.paymentsendpoint.model.Payments> {

    private static final String REST_PATH = "payments";

    /**
     * Create a request for the method "updatePayments".
     *
     * This request holds the parameters needed by the the paymentsendpoint server.  After setting any
     * optional parameters, call the {@link UpdatePayments#execute()} method to invoke the remote
     * operation. <p> {@link UpdatePayments#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.work.petcharity.paymentsendpoint.model.Payments}
     * @since 1.13
     */
    protected UpdatePayments(com.work.petcharity.paymentsendpoint.model.Payments content) {
      super(Paymentsendpoint.this, "PUT", REST_PATH, content, com.work.petcharity.paymentsendpoint.model.Payments.class);
    }

    @Override
    public UpdatePayments setAlt(java.lang.String alt) {
      return (UpdatePayments) super.setAlt(alt);
    }

    @Override
    public UpdatePayments setFields(java.lang.String fields) {
      return (UpdatePayments) super.setFields(fields);
    }

    @Override
    public UpdatePayments setKey(java.lang.String key) {
      return (UpdatePayments) super.setKey(key);
    }

    @Override
    public UpdatePayments setOauthToken(java.lang.String oauthToken) {
      return (UpdatePayments) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdatePayments setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdatePayments) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdatePayments setQuotaUser(java.lang.String quotaUser) {
      return (UpdatePayments) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdatePayments setUserIp(java.lang.String userIp) {
      return (UpdatePayments) super.setUserIp(userIp);
    }

    @Override
    public UpdatePayments set(String parameterName, Object value) {
      return (UpdatePayments) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Paymentsendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Paymentsendpoint}. */
    @Override
    public Paymentsendpoint build() {
      return new Paymentsendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link PaymentsendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setPaymentsendpointRequestInitializer(
        PaymentsendpointRequestInitializer paymentsendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(paymentsendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
